### ISSUE TITLE
Problem with overflow button in a right-aligned MenuBar

### ISSUE THREAD

**Issue by tarekoraby** [vaadin/vaadin-menu-bar#129]
If the MenuBar is right-aligned, the overflow button can be made to appear when the MenuBar content doesn't fit the page. However, when the window is expanded again, the overflow button remains visible despite the availability of space for the content.

To reproduce:

Assuming this view:

```
@Route("MenuBarView")
public class MenuBarView extends Div {

    public MenuBarView() {
        MenuBar menuBar = new MenuBar();
        Stream.of("Home", "Dashboard", "Content", "Structure", "Appearance", "Modules", "Users", "Configuration",
                "Reports", "Help").forEach(menuBar::addItem);
        add(menuBar);

        getStyle().set("overflow", "hidden");
        getStyle().set("border", "2px solid red");
        setWidthFull();
    }

}
```

And the following styling to the MenuBar:
```
:host {
  display: flex;
  justify-content: flex-end;
}
[part="container"] {
  width: auto;
}
```

Opening the view and then resizing the window so that the MenuBar's content wouldn't fit will show the overflow button. However, after expanding the window again, the overflow button will erroneously remain visible.

**Comment by jouni** [comment]
I wonder if this is considered supported use, changing the host element CSS like that? I would suggest to align the Menu Bar component using the parent layout/element.

**Comment by tarekoraby** [comment]
> I would suggest to align the Menu Bar component using the parent layout/element.

I couldn't get this approach to work either. Placing a MenuBar inside a parent Div (whose width is identical to the MenuBar) works fine when the page is shrunk (in which case the overflow bar is properly displayed). However, when the page is expanded again, the parent Div wouldn't expand again (hence the MenuBar wouldn't have enough space to show all buttons). 

Alternatively, if the parent Div has 100% width, then the overflow button wouldn't even show if the page is shrunk. I could trace this last behavior to [line 86](https://github.com/vaadin/vaadin-menu-bar/blob/5cecb5758bc8d1f7ef159f6843aeaf034939af02/src/vaadin-menu-bar-buttons-mixin.js#L86) of vaadin-menu-bar-buttons-mixin.js. If the container is left-aligned, then the `container.scrollWidth` is rightly greater than the `container.offsetWidth` (hence triggering the display of the overflow button). However, when the MenuBar is right-aligned, then for some reason `container.offsetWidth == container.scrollWidth` (and the overflow button is never shown)

**Comment by rolfsmeds** [comment]
As this issue describes an unsupported styling of the component, I'm closing it in favor of https://github.com/vaadin/vaadin-menu-bar/issues/131

However, I also noticed that the overlow menu does not seem to work correctly in certain layout configurations in which one might expect it to, so I also created a separate bug ticket about that: https://github.com/vaadin/vaadin-menu-bar/issues/130

**Comment by tarekoraby** [comment]
I understand that changing the MenuBar's internals to have its items right-aligned is currently not supported (hence #131 enhancement is required). But IMHO, the fact that MenuBar is not working properly if I make changes to its parent layout should be considered a bug in the MenuBar itself.

**Comment by tarekoraby** [comment]
Meanwhile, there is a rather hacky workaround that enables a right-aligned MenuBar to work properly. The idea is to add a JavaScript ResizeObserver on the parent layout of the MenuBar. This observer would then temporarily manipulate the MenuBar to take the full width of its parent and then trigger the calculation of the overflow button (after which, the full-width property is removed from the MenuBar again). Here's a simplified example:

```
MenuBar menuBar = new MenuBar();
Stream.of("Home", "Dashboard", "Content", "Structure", "Appearance", "Modules", "Users", "Configuration",
        "Reports", "Help").forEach(menuBar::addItem);

menuBar.getStyle().set("min-width", "0");

HorizontalLayout hl = new HorizontalLayout(menuBar);
hl.setWidthFull();
hl.getStyle().set("justify-content", "flex-end");
add(hl);

hl.getElement()
        .executeJs("const parentElement = $0;" 
                + "const menuElement = $1;" 
                + "function __handleOverflow() {"
                + " const parentScrollWidth = parentElement.scrollWidth;"
                + " menuElement.style.setProperty('width', '100%');" 
                + " menuElement.__detectOverflow();"
                + " menuElement.style.removeProperty('width', '100%');" 
                + "}"
                + "new ResizeObserver(__handleOverflow).observe(parentElement);", hl.getElement(),
                menuBar.getElement());
```
