### ISSUE TITLE
Using root components other than buttons

### ISSUE THREAD

**Issue by heruan** [vaadin/vaadin-menu-bar#13]
It would be useful to be able to use a root component other than a button, to create menus like the GitHub profile, i.e. with an avatar:

<img width="223" alt="Screen Shot 2019-03-13 at 15 22 51" src="https://user-images.githubusercontent.com/851745/54286324-eaa24680-45a3-11e9-8630-61b7292de30e.png">

Partly related to https://github.com/vaadin/vaadin-button/issues/86

**Comment by web-padawan** [comment]
The `tertiary-inline` theme variant allows you to place any component inside the button without being affected by its padding. The demo for it will be added in #58

**Comment by web-padawan** [comment]
Closing per above comment.
