### ISSUE TITLE
Responsive overflow feature doesn't work correctly without percentual width

### ISSUE THREAD

**Issue by rolfsmeds** [vaadin/vaadin-menu-bar#130]
The responsive overflow feature in Menu Bar, that collapses top-level items that oveflow the bar into a special overflow menu, only seems to work correctly with a percentual width, e.g. 100%.

While this is by far the most common configuration of the component, there are other layout configurations in which it the responsive overflow feature works partially, but not properly, e.g. by leaving its width undefined/auto, and making it shrink to fit its container using min-width instead:

```
<vaadin-horizontal-layout style="width:100%">
  <vaadin-menu-bar style="min-width:0;">...</vaadin-menu-bar>
</vaadin-horizontal-layout>
```

While the responsive overflow feature does kick in when the HL shrinks to smaller than the MenuBar's intrinsic width, and the overflow menu appears, the opposite does not work: as the HL grows back to accommodate the intrinsic width of the MenuBar, the overflow menu remains, instead of de-collapsing the top-level items.

**Comment by HawkSK** [comment]
Independently of this issue I have created a Vaadin Cookbook about the not so intuitive usage of the `MenuBar` overflow button, especially in a `HorizontalLayout`.
Essentially it contains the workaround to this issue which is basically to use `min-width` and `flex-grow: 1` (or `width: 100%` could work too I guess). However, this way the MenuBar grows beyond need.

In [this comment](https://github.com/vaadin/cookbook/pull/165#issuecomment-762403389) I have presented a hacky solution to keep MenuBar from growing way too much, so `HorizontalLayout` children could be justified as flex-start. I think if MenuBar would expose its `hasOverflow`* state this could be done nicely with css:
```css
:host([hasOverflow]) {
    flex-grow: 1;
    /* or maybe
    width: 100%
    */
}
```

---
\* MenuBar probably needs a new issue to expose `hasOverflow` state?
