### ISSUE TITLE
Changing items leaves ellipses button that points to old item

### ISSUE THREAD

**Issue by mvniemi** [vaadin/vaadin-menu-bar#133]
When changing the items array of a menu bar, specifically from a set of items that triggers the overflow ellipses to one that doesn't, the overflow ellipses button remains and contains the item from the previous menu set.

I have reproduced on glitch.com: https://glitch.com/edit/#!/vaadin-menu-bar-bugs?path=index.html%3A9%3A58

There is another issue open for ellipses, but it's unrelated to changing the items so I made this separate.

I'm working around this by destroying the menu-bar element and creating a new one when I need to change the items.

**Comment by sosa-vaadin** [comment]
This issue will be fixed when https://github.com/vaadin/vaadin-menu-bar/pull/134 is merged.
