### ISSUE TITLE
Consider styling root items to fill the buttons

### ISSUE THREAD

**Issue by pekam** [vaadin/vaadin-menu-bar#25]
If I have an item component with a click listener, the listener won't get fired when clicking on the edges of the button (outside the item). Styling `vaadin-context-menu-item` inside a `vaadin-menu-bar-button` to take the full size of the button could be useful in this sense.

This idea is mostly because of the Flow component, where click listeners can be added to `MenuItems`. If it makes no sense for the frontend users, we can go with a different kind of a workaround for Flow: listening for clicks in the buttons to fire clicks on the item.

Also, currently you can't listen for clicks in the item component at all, because the button stops propagation.

**Comment by heruan** [comment]
Not sure if related, but can I use a link as item (root but also not root)? Say I want an item to trigger a download, in Flow I'd do `new Anchor(streamResource, "Download")` but on the menu bar it should appear as button or dropdown item.

**Comment by pekam** [comment]
Yes, you can add any components in the root-level, and they will be wrapped inside buttons.

Right now anchors don't unfortunately work inside the buttons. Thanks for the use-case! I created another ticket #29
