### ISSUE TITLE
Sub-sub-menu closes immediately when opened on mobile

### ISSUE THREAD

**Issue by pekam** [vaadin/vaadin-menu-bar#27]
Steps to reproduce:
1. Go to "Nested Sub Menu" demo in https://cdn.vaadin.com/vaadin-menu-bar/1.0.0-alpha1/demo/#menu-bar-basic-demos
2. Open device mode in Chrome
3. Press "Project"
4. In the sub-menu, press "Users"
5. Notice how the second sub-menu opens and then both sub-menus are closed immediately

Tested also with a real mobile device.

The context-menu demo works fine, so the issue is in menu-bar.

**Comment by web-padawan** [comment]
Another mobile issue from https://github.com/vaadin/vaadin-menu-bar/issues/9#issuecomment-477531150

> Clicking a parent it item of a sub menu on mobile currently closes the component (instead of opening the sub-menu of that parent)

**Comment by pekam** [comment]
Ah, that probably describes the same issue, although it doesn't mention that the second sub-menu is briefly opened before closing everything.

**Comment by web-padawan** [comment]
Yes, I also thought it was related, if not the same. Thanks for clarification.
