### ISSUE TITLE
Highlight the currently open menu with Lumo tertiary theme

### ISSUE THREAD

**Issue by Legioth** [vaadin/vaadin-menu-bar#28]
As can be seen from the screenshot in https://github.com/vaadin/vaadin-menu-bar/issues/26, there's nothing that shows which top-level menu item is currently open. From the screenshot, one cannot be certain on whether it's the `File` or `Edit` menu that is currently shown.

For reference, see this screenshot from Google Docs where the open menu is visually highlighted.
![Screen Shot 2019-04-03 at 12 38 49](https://user-images.githubusercontent.com/1294657/55469158-8bb57780-560d-11e9-9a60-3cc0959f492b.png)

**Comment by web-padawan** [comment]
Note: this only applies to the `theme="tertiary"` so I renamed the issue accordingly.

**Comment by jouni** [comment]
Related: all the root items should have rounded corners (in all corners) in the tertiary variant.
