### ISSUE TITLE
Support having checked actions

### ISSUE THREAD

**Issue by Peppe** [vaadin/vaadin-menu-bar#34]
Some menu items are either on or off, like "show formula bar". Have an easy way to get those marked as checked when they are "on" and remove the check when they are "off".

![Screenshot 2019-04-04 at 8 58 06](https://user-images.githubusercontent.com/525503/55532803-d8558d00-56b7-11e9-85aa-e81d28c0905b.png)

**Comment by web-padawan** [comment]
The checkable items (in the submenu) are supported. To configure them, use the following code:

```
{text: 'Gridlines', checkable: true, checked: true}
```

I will create a new ticket for improving the demos to mention those.

**Comment by Peppe** [comment]
I didn't know that. Awesome!
