### ISSUE TITLE
Support disabling options.

### ISSUE THREAD

**Issue by Peppe** [vaadin/vaadin-menu-bar#35]
Make it possible to make some options in the menu disabled. These are not applicable at the time or you don't have permission to access them. They can be on top menu, sub items, or sub menus with children.

![Screenshot 2019-04-04 at 9 02 59](https://user-images.githubusercontent.com/525503/55532985-777a8480-56b8-11e9-8244-9d9ca0a92838.png)

**Comment by web-padawan** [comment]
The disabled options are supported. To configure them, set `disabled: true` on the item:

```
{text: 'Gridlines', disabled: true}
```

**Comment by Peppe** [comment]
Ah, I had tested `disable: true` but not `disabled: true`.
