### ISSUE TITLE
Support adding some kind of tag or additional component

### ISSUE THREAD

**Issue by Peppe** [vaadin/vaadin-menu-bar#36]
Sometimes you want to highlight a new item in your menus. For that you add a [new] tag or a ball next to the menu item to draw attention from the end user. Notice both parent and child in the image.

![Screenshot 2019-04-04 at 9 05 47](https://user-images.githubusercontent.com/525503/55533104-e2c45680-56b8-11e9-9792-eac26c2df223.png)

**Comment by web-padawan** [comment]
This is doable by using `item.component` or passing `<vaadin-context-menu-item>` directly:
https://github.com/vaadin/vaadin-menu-bar/blob/0a1ba952b4c9be0762e55880eab0b3ddb275a69a/src/vaadin-menu-bar-buttons-mixin.html#L171-L181
This is how MenuBar already works in Flow. So I don't think we need any additional API.
