### ISSUE TITLE
Support revealing more info on hover

### ISSUE THREAD

**Issue by Peppe** [vaadin/vaadin-menu-bar#37]
In google spreadsheet, if you hover over a function item, it will reveal the description of that function. It is useful to see if the function you found matches your needs.

![Screenshot 2019-04-04 at 9 08 50](https://user-images.githubusercontent.com/525503/55533243-52d2dc80-56b9-11e9-8ed8-c9d153f40b77.png)

**Comment by web-padawan** [comment]
This looks more like an application logic. It should be possible to achieve using `component` API for items, although it would also need some styling.

**Comment by web-padawan** [comment]
Closing per above comment. Please consider using `item.component` API.
