### ISSUE TITLE
Incorrectly select on hover

### ISSUE THREAD

**Issue by yuriy-fix** [vaadin/vaadin-menu-bar#48]
Menu-bar is incorrectly selecting the root level button on hover. Can be reproduced in `Open on Hover` demo example.

![hover-bug](https://user-images.githubusercontent.com/29372419/55805153-844b0e00-5ae6-11e9-83d5-b77f9be7f97a.gif)

**Comment by miladkdz** [comment]
Has this been fixed? I ran into it just today.

**Comment by pekam** [comment]
@miladkdz the fix should be included in `1.0.0-beta1`
