### ISSUE TITLE
Dropdown floats when scrolling

### ISSUE THREAD

**Issue by heruan** [vaadin/vaadin-menu-bar#50]
When scrolling the dropdown detaches from the menu-bar, leaving a floating list of orphaned items.

![vaadin-menu-bar-float](https://user-images.githubusercontent.com/851745/55867816-81eac180-5b83-11e9-937e-cc8299a51699.gif)

**Comment by web-padawan** [comment]
Thanks, that's a valid issue. I feel we also have to test it with submenu items exceeding height of the viewport, and probably lock the body scroll when submenu is opened.

**Comment by pekam** [comment]
Some observations of the native context menu behavior in Chrome:
- Scrolling on the overlay prevents page scrolling
- Scrolling outside the overlay depends on the platform:
  - Windows: closes the overlay and scrolls the page
  - Mac: prevents page scrolling

**Comment by jouni** [comment]
Preventing the page from scrolling is tricky on the web, without causing layout problems for the app, so I would avoid that approach.

Closing the overlay when the user scrolls is a potential usability issue, so I would also avoid that.

Also, our other components allow scrolling and keep the overlay attached, such as Combo Box, Date Picker and Select.

**Comment by heruan** [comment]
I agree with @jouni: why not just have the dropdown stick to the menubar? That's likely what a user expects.

**Comment by manolo** [comment]
be aware that not only scrolling but window resizing also has the issue
