### ISSUE TITLE
Rename ellipsis button to overflow button

### ISSUE THREAD

**Issue by tomivirkki** [vaadin/vaadin-menu-bar#53]
The naming of the feature is too explicit on the appearance (that it displays an ellipsis). Figure out better naming (for the themable part etc). Maybe "overflow-button" or something...

**Comment by tomivirkki** [comment]
Also, switch the implementation to use the ellipsis character in the theme instead of three dots "..." in the template

**Comment by web-padawan** [comment]
Let's add separate comments for the options below and vote with 👍 or 👎

**Comment by web-padawan** [comment]
Option 1: "overflow-button"

**Comment by web-padawan** [comment]
Option 2: "more-button"

**Comment by web-padawan** [comment]
Option 3: "show-all-button"
