### ISSUE TITLE
When using vaadin-context-menu-items as root-level components, overflowing items have incorrect styling

### ISSUE THREAD

**Issue by pekam** [vaadin/vaadin-menu-bar#71]
This is the case for the Flow component implementation. Overflowing items have `theme="menu-bar-item"` (added in #63), which causes the item text contents to be centered in the overflow overlay. If this `theme` attribute is relevant only when the item is inside a button, it should be cleared when the item overflows.

**Comment by web-padawan** [comment]
The theme is also relevant for icons but I agree that centering should be avoided in overflow submenu.
Will try to use `inherit` for flex alignment properties and see if that helps.
