### ISSUE TITLE
Implement Lumo & Material themes

### ISSUE THREAD

**Issue by tomivirkki** [vaadin/vaadin-menu-bar#8]
child of [vaadin/vaadin-core#208](https://github.com/vaadin/vaadin-core/issues/208)

DoD:
- I can use button theme variants on the menu so that all root level buttons are affected

The appearance of the component should be as follows on Lumo:
<img width="641" alt="menubar-lumo" src="https://user-images.githubusercontent.com/1222264/53169683-9e886580-35e6-11e9-9f92-1951f7f78fd7.png">

**Comment by tomivirkki** [comment]
@jouni how about the MD appearance?

**Comment by jouni** [comment]
Quick mockups:

![menubar-material-theme](https://user-images.githubusercontent.com/66382/53495780-4a2f2b00-3aa9-11e9-95bd-5ea96577cdd8.png)

I think Lumo’s tertiary buttons should follow the same visual style as the default Material button style, where all the buttons still have rounded corners all around.
