### ISSUE TITLE
Primary button variant has too low contrast for the expanded button

### ISSUE THREAD

**Issue by jouni** [vaadin/vaadin-menu-bar#87]
<img width="363" alt="Screenshot 2019-08-15 at 9 58 38" src="https://user-images.githubusercontent.com/66382/63078166-5453c180-bf43-11e9-8900-5d4317aa3b95.png">

Rather than setting the background color of the host element, we could use one of the pseudo-elements, the same which is used for the hover effect. Instead of lightening, it should probably get darker when expanded.

**Comment by web-padawan** [comment]
Closing in favor of https://github.com/vaadin/vaadin-web-components/issues/119 which describes the same problem.
