### ISSUE TITLE
Make sure the component is accessible

### ISSUE THREAD

**Issue by tomivirkki** [vaadin/vaadin-menu-bar#9]
child of [vaadin/vaadin-core#208](https://github.com/vaadin/vaadin-core/issues/208)

Make sure keyboard navigation works as expected.
Make sure the component works with screen readers as expected.
See that the aria roles follow https://www.w3.org/WAI/tutorials/menus/application-menus-code/

**Comment by web-padawan** [comment]
Note: <kbd>Esc</kbd> should probably close sub-menu and focus menu bar button again

**Comment by tomivirkki** [comment]
Also fix the following issues:
- Hovering over a root level item should open the sub-menu of that item if the component is in opened state. This works for the sub-menus currently but not on the root level.
- Clicking a parent it item of a sub menu currently closes the component (instead of opening the sub-menu of that parent)

**Comment by web-padawan** [comment]
> Hovering over a root level item should open the sub-menu of that item if the component is in opened state. This works for the sub-menus currently but not on the root level.

Fixed by #23 

And https://github.com/vaadin/vaadin-menu-bar/issues/9#issuecomment-477059015 is to be fixed by #24 

> Clicking a parent it item of a sub menu on mobile currently closes the component (instead of opening the sub-menu of that parent)
Will submit a separate PR for that.

**Comment by web-padawan** [comment]
Keyboard navigation and roles to be implemented in according to WAI ARIA guidelines:
https://www.w3.org/TR/wai-aria-practices-1.1/examples/menubar/menubar-1/menubar-1.html
