### ISSUE TITLE
Sub-menu is displayed wrong place(at corner at browser) after clicking vaadin-menu-bar, instead of below its' parent menu clicked.

### ISSUE THREAD

**Issue by hongduc-phan** [vaadin/vaadin-menu-bar#96]
Sub-menu is displayed wrong place(at the corner at browser) after clicking `vaadin-menu-bar`, instead of below its' parent menu clicked, in the first render of context-menu. After a user clicked menu, the sub-menu is displayed below the menu, but actually it is displayed at the corner of the browser and after under 1 second, it moves to the right place-under the menu clicked.
 From the second click, the coordinate of the sub-menu (context-menu) will be displayed in the old coordinate of the previous sub-menu

**Comment by web-padawan** [comment]
Fixed by https://github.com/vaadin/vaadin-context-menu/pull/260
